name: My GitHub Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a script
        run: echo "Workflow Triggered"
